prost-build will not compile because protoc is missing.
prost-build seems to be trying to build protoc, but it needs cmake to do this.
Rather than install that whole toolchain, install protoc.

```
running: "cmake" "/Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.3/third-party/protobuf/cmake" "-DCMAKE_INSTALL_PREFIX=/usr/local/Homebrew/Library/Taps/momentohq/homebrew-tap/archive-0.23.6/target/release/build/prost-build-8d5be0c1b43712a2/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64 -arch x86_64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?
```

Also, only upload the bottles if it worked.